import { useShallow } from "zustand/react/shallow";

import { useAppUiStore } from "./appUiStore";

export function useAppUiState() {
  return useAppUiStore(
    useShallow((state) => ({
      capabilities: state.capabilities,
      baseState: state.baseState,
      config: state.config,
      reporterSnapshot: state.reporterSnapshot,
      discordSnapshot: state.discordSnapshot,
      platformSelfTest: state.platformSelfTest,
      notices: state.notices,
      hydrated: state.hydrated,
      busy: state.busy,
      activeSection: state.activeSection,
      activeRuleIndex: state.activeRuleIndex,
      rulesImportOpen: state.rulesImportOpen,
      rulesImportValue: state.rulesImportValue,
      blacklistInput: state.blacklistInput,
      whitelistInput: state.whitelistInput,
      nameOnlyInput: state.nameOnlyInput,
      mediaSourceInput: state.mediaSourceInput,
      rulesDialogOpen: state.rulesDialogOpen,
      customRulesDialogOpen: state.customRulesDialogOpen,
      customPresetPage: state.customPresetPage,
      activeCustomPresetIndex: state.activeCustomPresetIndex,
      appliedCustomPresetIndex: state.appliedCustomPresetIndex,
      discordDetailsForceCustomChoice: state.discordDetailsForceCustomChoice,
      discordStateForceCustomChoice: state.discordStateForceCustomChoice,
      presetDetailsForceCustomChoice: state.presetDetailsForceCustomChoice,
      presetStateForceCustomChoice: state.presetStateForceCustomChoice,
      discardDialogOpen: state.discardDialogOpen,
      appliedRuntimeConfigSignature: state.appliedRuntimeConfigSignature,
      ruleGroupPage: state.ruleGroupPage,
      titleRulePage: state.titleRulePage,
      runtimeLogPage: state.runtimeLogPage,
      jsonViewer: state.jsonViewer,
      setCapabilities: state.setCapabilities,
      setBaseState: state.setBaseState,
      setConfig: state.setConfig,
      setReporterSnapshot: state.setReporterSnapshot,
      setDiscordSnapshot: state.setDiscordSnapshot,
      setPlatformSelfTest: state.setPlatformSelfTest,
      setHydrated: state.setHydrated,
      setBusy: state.setBusy,
      setActiveSection: state.setActiveSection,
      setActiveRuleIndex: state.setActiveRuleIndex,
      setRulesImportOpen: state.setRulesImportOpen,
      setRulesImportValue: state.setRulesImportValue,
      setBlacklistInput: state.setBlacklistInput,
      setWhitelistInput: state.setWhitelistInput,
      setNameOnlyInput: state.setNameOnlyInput,
      setMediaSourceInput: state.setMediaSourceInput,
      setRulesDialogOpen: state.setRulesDialogOpen,
      setCustomRulesDialogOpen: state.setCustomRulesDialogOpen,
      setCustomPresetPage: state.setCustomPresetPage,
      setActiveCustomPresetIndex: state.setActiveCustomPresetIndex,
      setAppliedCustomPresetIndex: state.setAppliedCustomPresetIndex,
      setDiscordDetailsForceCustomChoice: state.setDiscordDetailsForceCustomChoice,
      setDiscordStateForceCustomChoice: state.setDiscordStateForceCustomChoice,
      setPresetDetailsForceCustomChoice: state.setPresetDetailsForceCustomChoice,
      setPresetStateForceCustomChoice: state.setPresetStateForceCustomChoice,
      setDiscardDialogOpen: state.setDiscardDialogOpen,
      setAppliedRuntimeConfigSignature: state.setAppliedRuntimeConfigSignature,
      setRuleGroupPage: state.setRuleGroupPage,
      setTitleRulePage: state.setTitleRulePage,
      setRuntimeLogPage: state.setRuntimeLogPage,
      setJsonViewer: state.setJsonViewer,
      addNotice: state.addNotice,
      removeNotice: state.removeNotice,
    })),
  );
}
